config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :cryptocurrencies
  resources :calculator
  resources :matyaka_data_records
  get 'matyaka_data_entry', to: 'matyaka_data_records#new'
  get 'matyaka_data_search', to: 'matyaka_data_records#index'
  get 'crypto', to: 'cryptocurrencies#crypto'
  get 'websocket', to: 'cryptocurrencies#websocket'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100" },
                    :deault_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user! # Can limit to specific actions by using ,only: [:new, :edit]
  before_action :only_current_user
  
  # GET to /users/:users/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
  # POST request to /user/:user_id/profile
  def create
    # Ensure that we have user who is filling out form
    @user = User.find( params[:user_id] )
    # Create profile linked to this specific user
    @profile = @user.build_profile( profile_params )
    if @profile.save
      flash[:sucess] = "Profile updated!"
      redirect_to user_path( id: params[:user_id] )
    else
      render action: :new
    end
  end
  
  # GET to /users/:user_id/profile/edit
  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end
  
  #PUT to /users/:user_id/profile
  def update
    #Retrieve the user from db
    @user = User.find ( params[:user_id] )
    #Retreve taht user's profile
    @profile = @user.profile
    #Mass assign edited profile attributes and save (update)
    if @profile.update_attributes(profile_params)
      flash[:sucess] = "Profile updated!"
      #Redirect user to their profile page
      redirect_to user_path( id: params[:user_id] )
    else
      render action: :edit
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title,
        :phone_number, :contact_email, :description)
    end
    
    def only_current_user
      @user = User.find ( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit Your Profile</h1>
      <p class="text-center">Be a part of the DevMatch community and fill out your profile!</p>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Create Your Profile</h1>
      <p class="text-center">Be a part of the DevMatch community and fill out your profile!</p>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>