config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :cryptocurrencies
  resources :calculator
  resources :matyaka_data_records
  get 'matyaka_data_entry', to: 'matyaka_data_records#new'
  get 'matyaka_data_search', to: 'matyaka_data_records#index'
  get 'crypto', to: 'cryptocurrencies#crypto'
  get 'websocket', to: 'cryptocurrencies#websocket'
end

app/models/matyaka_data_record.rb
class MatyakaDataRecord < ActiveRecord::Base
  validates :account_name, presence: true
  validates :site_url_address, presence: true
  validates :advertising_group, presence: true
  validates :remaining_funds, presence: true
end

app/controllers/matyaka_data_records_controller.rb
class MatyakaDataRecordsController < ApplicationController
  
  def index
    @matyaka_data_records = MatyakaDataRecord.where("
                                                      account_name LIKE ?
                                                      OR 
                                                      site_url_address LIKE ?
                                                      OR
                                                      advertising_group LIKE ?
                                                      OR
                                                      remaining_funds LIKE ?
                                                    ",
                                                      "%#{params[:search]}%",
                                                      "%#{params[:search]}%",
                                                      "%#{params[:search]}%",
                                                      "%#{params[:search]}%"
                                                    )
  end
  
  def show
  end
  
  def new
    @matyaka_data_record = MatyakaDataRecord.new
  end
  
  def edit
  end
  
  def create
    @matyaka_data_record = MatyakaDataRecord.new(data_params)
    if @matyaka_data_record.save
      flash[:success] = "Data Saved"
      redirect_to matyaka_data_entry_path
    else
      flash[:danger] = @matyaka_data_record.errors.full_messages.join(", ")
      redirect_to matyaka_data_entry_path
    end
  end
  
  def destroy
    @matyaka_data_record.destroy
  end
  
  def update
    @matyaka_data_record.update(data_params)
  end
    
  private
    def data_params
      params.require(:matyaka_data_record).permit(
                                                  :account_name,
                                                  :site_url_address,
                                                  :advertising_group,
                                                  :remaining_funds
                                                  )
    end
end

app/views/matyaka_data_records/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        <h2 class="text-center">Data Search</h2></br>
        <%= form_tag matyaka_data_records_path, :method => 'get' do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], class: 'form-control'%>
            <%= submit_tag "Search", class: 'btn btn-default' %>
          </div>
        <% end %>
        </br>
      </div>
    </div>
    </br></br>

      <div class="col-md-12">
        <div class="well">
          <table class="table table-condensed">
            <thread>
              <tr>
                <th>Account Name</th>
                <th>Site URL Address</th>
                <th>Advertising Group</th>
                <th>Remaining Funds</th>
              </tr>
            </thread>
            
            <tbody>
              <% @matyaka_data_records.each do |record| %>
                <tr>
                  <td><%= record.account_name %></td>
                  <td><%= record.site_url_address %></td>
                  <td><%= record.advertising_group %></td>
                  <td><%= record.remaining_funds %></td>
                  <td><%= link_to 'Edit', edit_matyaka_data_record_path(record), class: 'btn btn-default' %></td>
                  <td><%= link_to 'Delete', record, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
  </div>
</div>

app/views/matyaka_data_records/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Matyaka's Data Entry Page</h3>
    
    <div class="col-md-12">
      <div class="well">
        <%= form_for @matyaka_data_record do |f| %>
          <div class="form-group">
            <%= f.label :account_name %>
            <%= f.text_field :account_name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :site_url_address %>
            <%= f.text_field :site_url_address, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :advertising_group %>
            <%= f.text_field :advertising_group, class: 'form-control' %>
          </div>
        
          <div class="form-group">
            <%= f.label :remaining_funds %>
            <%= f.text_field :remaining_funds, class: 'form-control' %>
          </div>
        
        
          <%= f.submit 'Save', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>