config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :cryptocurrencies
  resources :calculator
  resources :matyaka_data_records
  get 'matyaka_data_entry', to: 'matyaka_data_records#new'
  get 'matyaka_data_search', to: 'matyaka_data_records#index'
  get 'crypto', to: 'cryptocurrencies#crypto'
  get 'websocket', to: 'cryptocurrencies#websocket'
end

app/views/pages/about.html.erb
<div class="container text-center">
  <h1>About Us</h1>
  <p>
    We are DevMatch. Our company focuses on creating an exclusive community
    for developers and entrepreneurs to meet.
  </p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">    
  <h1>Welome to DevMatch</h1>
  <h3>A membership site where entrepreneurs can meet developers</h3>
</div>
<div class="container home-signup-links">
  <div class="row">
    <% if user_signed_in? %>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Your Profile</h2>
          <% if current_user.profile %>
            <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id),
              class: 'btn btn-default btn-lg btn-block' %>
            <%= link_to "View your profile", user_path(id: current_user.id),
              class: 'btn btn-default btn-lg btn-block' %>
          <% else %>
            <p>Create your profile so that you can share your information with the community</p>
            <%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id),
              class: 'btn btn-default btn-lg btn-block' %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">The Community</h2>
          <p>Visit the community to meet other developers, entrepreneurs and investors!</p>
          <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
        </div>
      </div>
    <% else %>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Basic membership</h2>
          <h4>Sign up for free and get basic acecess to the community</h4>
          <br>
          <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id),
            class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Pro membership</h2>
          <h4>Sign up for the pro account for $10/month and get acess to the community and contact information!</h4>
          <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id),
            class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
</div>