config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :cryptocurrencies
  resources :calculator
  resources :matyaka_data_records
  get 'matyaka_data_entry', to: 'matyaka_data_records#new'
  get 'matyaka_data_search', to: 'matyaka_data_records#index'
  get 'crypto', to: 'cryptocurrencies#crypto'
  get 'websocket', to: 'cryptocurrencies#websocket'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navibar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target="#main-nav-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            DevMatch
          <% end %>
        </div>
        
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete,
                class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Community", users_path %></li>
              <li><%= link_to "My account", edit_user_registration_path %></li>
            <% end %>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
            
            <li><%= link_to "Coinbase", new_cryptocurrency_path %></li>
            <li><%= link_to "GDAX", crypto_path %></li>
            <!--<li><%= link_to "Socket", websocket_path %></li>-->
            <!--<li><%= link_to "Calculator", calculator_index_path %></li>-->
            <li><%= link_to "Matyaka Data Entry", matyaka_data_entry_path %></li>
            <li><%= link_to "Matyaka Data Search", matyaka_data_search_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    
    <div class = "container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
  
    <%= yield %>

  </body>
</html>